// Code generated by goctl. DO NOT EDIT.
package types

import "mime/multipart"

type Login struct {
	Username string         `form:"username,optional" json:"username,optional" `
	Password string         `form:"password,optional" json:"password,optional"`
	File     multipart.File `form:"file,optional" json:"file,optional"`
}

type UserToken struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type NewToken struct {
	Name         string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
